name: Java CI with Snyk,Maven,Docker

on:
 workflow_dispatch:
   inputs:
     DockerImageName:
       description: 'Docker image name'
       default: 'devsecops'
       required: true 
     tag:
       description: Docker tag
       default: latest
       required: true
jobs:
        
  Push_to_GCR:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1 

      - name: Login to GCR
        env:
          PROJECT_ID: nitor-tes 
        uses: google-github-actions/setup-gcloud@v0.3.0 
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }} #parse the value of repository secret called SERVICE_ACCOUNT_KEY that we have created earlier
          project_id: ${{ env.PROJECT_ID }} #parse the value of env called PROJECT_ID
          export_default_credentials: true
         
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml


      - name: Build Docker Image
        env:
          PROJECT_ID: nitor-tes
        run: docker build -t ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} . 
        
      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet 
        
      - name: Push Docker Image to Container Registry GCR
        env: 
          PROJECT_ID: nitor-tes
        run: |-
          docker tag ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} gcr.io/$PROJECT_ID/${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} 
          docker push gcr.io/$PROJECT_ID/${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}}       
